live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 12.0

[font.bold]
family = "Menlo"

[font.italic]
family = "Menlo"

[font.normal]
family = "Menlo"

[shell]
program = "/bin/zsh"

[window]
decorations = "none"
startup_mode = "Windowed"
