#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    # selected=$(find ~/src/work -mindepth 1 -maxdepth 4 -type f -d -not \( -path "*/node_modules/*" -or -path "*/.yarn/*" -or -path "*/lib/*" -or -path "*/dist/*" -or -path "*/.git/*" -or -path "*/.sl/*" -or -path "*/.github/*" -prune \) \( -name ".pj" \) -print -prune | uniq | xargs -n1 dirname | sort | fzf --height 30%)
    selected=$(find ~/src/ -mindepth 1 -maxdepth 4 -type f -d -not \( -path "*/node_modules/*" -or -path "*/.yarn/*" -or -path "*/lib/*" -or -path "*/dist/*" -or -path "*/.git/*" -or -path "*/.sl/*" -or -path "*/.github/*" -prune \) \( -name ".poop" \) -print -prune | uniq | xargs -n1 dirname | sort | fzf --height 30%)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(echo "$selected" | tr . _ | tr - _ | rev | cut -d/ -f1 -f2 | rev)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2>/dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name

#find ~/src/personal -mindepth 1 -maxdepth 4 -type d -d \
#-not \( -path "*/node_modules/*" -or  \
#        -path "*/.yarn/*" -or  \
#        -path "*/lib/*" -or \
#        -path "*/dist/*" -or \
#        -path "*/.git/*" -or \
#        -path "*/.github/*" \)  \
#-prune \
#-exec test -e '{}/.pkeep' ';' \
#-or -exec test -e '{}/package.json' ';' \
#-or -exec test -d '{}/.git' ';' \
#-print -prune  

# find ~/src -mindepth 1 -maxdepth 4 -type f -d -not \( -path "*/node_modules/*" -or -path "*/.yarn/*" -or -path "*/lib/*" -or -path "*/dist/*" -or -path "*/.git/*" -or -path "*/.sl/*" -or -path "*/.github/*" -prune \) \( -name "package.json" -or -name ".git" \) -print -prune | uniq | xargs n1 dirname | sort | fzf --height 30%
# find ~/src -mindepth 1 -maxdepth 4 -type f -d \ -not \( -path "*/node_modules/*" -or  \ -path "*/.yarn/*" -or  \ -path "*/lib/*" -or \ -path "*/dist/*" -or \ -path "*/.git/*" -or \ -path "*/.sl/*" -or \ -path "*/.github/*" -prune \)  \ \( -name "package.json" -or -name ".git" \) \ -print -prune | uniq | xargs n1 dirname | sort
