#!/usr/bin/env bash

# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config layout bsp

yabai -m config window_placement second_child

yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 0
yabai -m config right_padding 0
yabai -m config window_gap 0
yabai -m config window_shadow off

yabai -m config mouse_follows_focus off

yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

yabai -m mouse_drop_action swap

yabai -m rule --add app="^1Password$" manage=off sticky=on layer=above
yabai -m rule --add app="^System Preference$" manage=off sticky=on layer=above
yabai -m rule --add app="^Karabiner-Element$" manage=off sticky=on layer=above
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off sticky=on layer=above
yabai -m rule --add app="^Finder$" manage=off sticky=on layer=above
yabai -m rule --add app="^Activity Monitor$" manage=off sticky=on layer=above
yabai -m rule --add app="^Spotify$" manage=off sticky=on layer=above
yabai -m rule --add app="^System Information$" manage=off sticky=on layer=above

# function setup_space {
#   local idx="$1"
#   local name="$2"
#   local space=
#   echo "setup space $idx : $name"
#
#   space=$(yabai -m query --spaces --space "$idx")
#   if [ -z "$space" ]; then
#     yabai -m space --create
#   fi
#
#   yabai -m space "$idx" --label "$name"
# }
#
# setup_space 1 main
# setup_space 2 side
# setup_space 3 slack
# # setup_space 4 media
# # setup_space 5 other
#
# yabai -m rule --add app="^Alacritty$" space=1
# # yabai -m rule --add app="^Google Chrome$" space=^2
# yabai -m rule --add app="^Slack$" space=2
# # yabai -m rule --add app="^Spotify$" space=4
